### ISSUE TITLE
请问为什么设置UICollectionView Header  不显示？。

### ISSUE THREAD

**Issue by money150604** [cuzv/ThinningCoordinator#1]
RT

**Comment by cuzv** [comment]
更新了示例代码，你看看。

**Comment by money150604** [comment]
真是很奇怪，，按照你写的demo  我设置下去  size打印 一直是 0，0，tableView设置的话是正常的

**Comment by cuzv** [comment]
header/footer 还是 cell 的 size 为 {0, 0}?
PS: 如果header/footer没有配置数据的话对应的section返回的就是 {0, 0}

**Comment by money150604** [comment]
![image](https://cloud.githubusercontent.com/assets/12742817/17211866/551d837e-54fe-11e6-8b1e-90d0b74b4339.png)
header size 为　｛0,0｝

**Comment by money150604** [comment]
解决了  谢谢你

**Comment by cuzv** [comment]
👏 太客气了，我什么忙也没有帮上。
